# Generated by Django 3.2.6 on 2021-11-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetext',
            name='title',
        ),
        migrations.AlterField(
            model_name='filetext',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
