# Generated by Django 3.2.6 on 2021-11-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sped', '0002_auto_20211104_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetext',
            name='file',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
